
export const GET_INGREDIENTS = 'GET_INGREDIENTS';
export const UPDATE_STOCK = 'UPDATE_STOCK';

export const CREATE_INGREDIENST_REQUEST = "CREATE_INGREDIENST_REQUEST";
export const CREATE_INGREDIENST_SUCCESS = "CREATE_INGREDIENST_SUCCESS";
export const CREATE_INGREDIENST_FAILURE = "CREATE_INGREDIENST_FAILURE";  


export const CREATE_INGREDIENST_CATEGORY_REQUEST = "CREATE_INGREDIENST_CATEGORY_REQUEST";
export const CREATE_INGREDIENST_CATEGORY_SUCCESS = "CREATE_INGREDIENST_CATEGORY_SUCCESS";
export const CREATE_INGREDIENST_CATEGORY_FAILURE = "CREATE_INGREDIENST_CATEGORY_FAILURE";  


export const GET_INGREDIENST_CATEGORY_REQUEST = "GET_INGREDIENST_CATEGORY_REQUEST";
export const GET_INGREDIENST_CATEGORY_SUCCESS = "GET_INGREDIENST_CATEGORY_SUCCESS";
export const GET_INGREDIENST_CATEGORY_FAILURE = "GET_INGREDIENST_CATEGORY_FAILURE";  




