export const CREATE_RESTUARANT_REQUEST = "CREATE_RESTUARANT_REQUEST";
export const CREATE_RESTUARANT_SUCCESS = "CREATE_RESTUARANT_SUCCESS";
export const CREATE_RESTUARANT_FAILURE = "CREATE_RESTUARANT_FAILURE";

export const GET_ALL_RESTUARANTS_REQUEST = "GET_ALL_RESTUARANTS_REQUEST";
export const GET_ALL_RESTUARANTS_SUCCESS = "GET_ALL_RESTUARANTS_SUCCESS";
export const GET_ALL_RESTUARANTS_FAILURE = "GET_ALL_RESTUARANTS_FAILURE";

export const DELETE_RESTUARANT_REQUEST = "DELETE_RESTUARANT_REQUEST";
export const DELETE_RESTUARANT_SUCCESS = "DELETE_RESTUARANT_SUCCESS";
export const DELETE_RESTUARANT_FAILURE = "DELETE_RESTUARANT_FAILURE";

export const UPDATE_RESTUARANT_REQUEST = "UPDATE_RESTUARANT_REQUEST";
export const UPDATE_RESTUARANT_SUCCESS = "UPDATE_RESTUARANT_SUCCESS";
export const UPDATE_RESTUARANT_FAILURE = "UPDATE_RESTUARANT_FAILURE";

export const GET_RESTUARANT_BY_ID_REQUEST = "GET_RESTUARANT_BY_ID_REQUEST";
export const GET_RESTUARANT_BY_ID_SUCCESS = "GET_RESTUARANT_BY_ID_SUCCESS";
export const GET_RESTUARANT_BY_ID_FAILURE = "GET_RESTUARANT_BY_ID_FAILURE";

export const GET_RESTUARANT_BY_USER_ID_REQUEST = "GET_RESTUARANT_BY_USER_ID_REQUEST";
export const GET_RESTUARANT_BY_USER_ID_SUCCESS = "GET_RESTUARANT_BY_USER_ID_SUCCESS";
export const GET_RESTUARANT_BY_USER_ID_FAILURE = "GET_RESTUARANT_BY_USER_ID_FAILURE";

export const UPDATE_RESTUARANT_STATUS_REQUEST = "UPDATE_RESTUARANT_STATUS_REQUEST";
export const UPDATE_RESTUARANT_STATUS_SUCCESS = "UPDATE_RESTUARANT_STATUS_SUCCESS";
export const UPDATE_RESTUARANT_STATUS_FAILURE = "UPDATE_RESTUARANT_STATUS_FAILURE";

export const CREATE_EVENTS_REQUEST = "CREATE_EVENTS_REQUEST";
export const CREATE_EVENTS_SUCCESS = "CREATE_EVENTS_SUCCESS";
export const CREATE_EVENTS_FAILURE = "CREATE_EVENTS_FAILURE";

export const GET_ALL_EVENTS_REQUEST = "GET_ALL_EVENTS_REQUEST";
export const GET_ALL_EVENTS_SUCCESS = "GET_ALL_EVENTS_SUCCESS";
export const GET_ALL_EVENTS_FAILURE = "GET_ALL_EVENTS_FAILURE";

export const DELETE_EVENTS_REQUEST = "DELETE_EVENTS_REQUEST";
export const DELETE_EVENTS_SUCCESS = "DELETE_EVENTS_SUCCESS";
export const DELETE_EVENTS_FAILURE = "DELETE_EVENTS_FAILURE";

export const GET_RESTUARANTS_EVENTS_REQUEST = "GET_RESTUARANS_EVENTS_REQUEST";
export const GET_RESTUARANTS_EVENTS_SUCCESS = "GET_RESTUARANS_EVENTS_SUCCESS";
export const GET_RESTUARANTS_EVENTS_FAILURE = "GET_RESTUARANS_EVENTS_FAILURE";

export const CREATE_CATEGORY_REQUEST = "CREATE_CATEGORY_REQUEST";
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";
export const CREATE_CATEGORY_FAILURE = "CREATE_CATEGORY_FAILURE";

export const GET_RESTUARANTS_CATEGORY_REQUEST = "GET_RESTUARANS_CATEGORY_REQUEST";
export const GET_RESTUARANTS_CATEGORY_SUCCESS = "GET_RESTUARANS_CATEGORY_SUCCESS";
export const GET_RESTUARANTS_CATEGORY_FAILURE = "GET_RESTUARANS_CATEGORY_FAILURE";